In [ ]:
f = np.arange(1, 2, 0.3, dtype=float)

c = np.array([False, False, True])

b = np.array(1, 2, 3, 4, 5, dtype=float)

b = np.array([1, 2, 3, 4, 5], dtype=float)

In [1]:
import numpy as np

In [2]:
np.arange(1, 2, 0.3, dtype=float)

array([ 1. ,  1.3,  1.6,  1.9])

In [3]:
np.array([False, False, True])

array([False, False,  True], dtype=bool)

In [4]:
np.array(1, 2, 3, 4, 5, dtype=float)

ValueError: only 2 non-keyword arguments accepted

In [5]:
np.array([1, 2, 3, 4, 5], dtype=float)

array([ 1.,  2.,  3.,  4.,  5.])

In [ ]:
np.linalg.norm(a, ord=2) - np.linalg.norm(b, ord=2)
scipy.spatial.distance.cdist(a[np.newaxis, :], b[np.newaxis, :], metric='euclidean')
scipy.spatial.distance.cdist(b, a, metric='euclidean')
scipy.spatial.distance.cdist(a[:, np.newaxis], b[:, np.newaxis], metric='euclidean')

In [12]:
from scipy import spatial
a = np.array([6, 3, -5])
b = np.array([-1, 0, 7])

In [9]:
np.linalg.norm(a, ord=2) - np.linalg.norm(b, ord=2)

1.2955324534752801

In [13]:
spatial.distance.cdist(a[np.newaxis, :], b[np.newaxis, :], metric='euclidean')

array([[ 14.2126704]])

In [14]:
spatial.distance.cdist(b, a, metric='euclidean')

ValueError: XA must be a 2-dimensional array.

In [15]:
spatial.distance.cdist(a[:, np.newaxis], b[:, np.newaxis], metric='euclidean')

array([[  7.,   6.,   1.],
       [  4.,   3.,   4.],
       [  4.,   5.,  12.]])

In [ ]:
np.dot(a, b)
b.dot(a)
np.dot(a, b) / np.linalg.norm(a) / np.linalg.norm(b)
a * b

In [17]:
a = np.array([0, -1, 11])
b = np.array([3, 7, 2])

In [19]:
np.dot(a, b)

15

In [20]:
b.dot(a)

15

In [21]:
np.dot(a, b) / np.linalg.norm(a) / np.linalg.norm(b)

0.17247076868185271

In [22]:
a * b

array([ 0, -7, 22])

In [ ]:
a = a[:, np.newaxis]
a = a.reshape((1, 5))
a = a.reshape((5, 1))
a = a[np.newaxis, :]

In [28]:
a = np.array([8, 10, -1, 0, 0])
a

array([ 8, 10, -1,  0,  0])

In [26]:
a[:, np.newaxis]

array([[ 8],
       [10],
       [-1],
       [ 0],
       [ 0]])

In [27]:
a.reshape((1, 5))

array([[ 8, 10, -1,  0,  0]])

In [29]:
a.reshape((5, 1))

array([[ 8],
       [10],
       [-1],
       [ 0],
       [ 0]])

In [30]:
a[np.newaxis, :]

array([[ 8, 10, -1,  0,  0]])