In [ ]:
e = np.arange(1, 13, 2).reshape((3, 2))
d = np.ones((10, 10))
b = np.eye(2, 3)
c = np.eye((4, 5))
a = np.array([4, 3, 2], [2, 9, 1], [3, 1, 9])

In [1]:
import numpy as np

In [2]:
np.arange(1, 13, 2).reshape((3, 2))

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [7]:
np.arange(1, 13, 2)

array([ 1,  3,  5,  7,  9, 11])

In [3]:
np.ones((10, 10))

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [4]:
np.eye(2, 3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.]])

In [5]:
np.eye((4, 5))

TypeError: an integer is required

In [6]:
np.array([4, 3, 2], [2, 9, 1], [3, 1, 9])

ValueError: only 2 non-keyword arguments accepted

In [12]:
a = np.eye(4, 5)
a[[0, 3], [1, 3]]

array([ 0.,  1.])

In [9]:
a

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.]])

In [15]:
a[1, 3]

0.0

In [14]:
a(0, 1)

TypeError: 'numpy.ndarray' object is not callable

In [ ]:
np.linalg.inv(.

np.linalg.det(...)

np.det(...)

np.inv(...)

np.transpose(...)

In [22]:
?np.linalg.det

In [23]:
a = np.array([[1, 2], [3, 4]])
np.linalg.det(a)

-2.0000000000000004

In [25]:
?np.solve
?np.linalg.eig(...)
# np.linalg.matrix_rank(...)
# np.linalg.solve(...)
# np.eig(...)

Object `np.solve` not found.
